version: "2"
services:

  nginx:
    image: samanthajayasinghe/php-dev-env-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
       - php-dev
    restart: always
    container_name: os_dev_nginx

  php-5.6:
    image: samanthajayasinghe/php-dev-env-php56
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev
    restart: always
    container_name: os_dev_php56

  php-7.0:
    image: samanthajayasinghe/php-dev-env-php70
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev
    restart: always
    container_name: os_dev_php70

  php-7.1:
    image: samanthajayasinghe/php-dev-env-php71
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev
    restart: always
    container_name: os_dev_php71

  php-7.2:
     image: samanthajayasinghe/php-dev-env-php72
     working_dir: ${REMOTE_SRC}
     environment:
       HIST_FILE: /root/.bash_history
     volumes:
       - ${LOCAL_SRC}:${REMOTE_SRC}
       - $HOME/.bash_history:/root/.bash_history
     networks:
       - php-dev
     restart: always
     container_name: os_dev_php72

  mysql57:
    image: mysql:5.7
    ports:
      - "${MYSQL_57_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mysql-data-56:/var/lib/mysql/57
    depends_on:
          - nginx
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mysql57

  mysql56:
    image: mysql:5.6
    ports:
      - "${MYSQL_56_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mysql-data-57:/var/lib/mysql/56
    depends_on:
          - nginx
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mysql56

  mysql55:
    image: mysql:5.5
    ports:
      - "${MYSQL_55_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mysql-data-55:/var/lib/mysql/55
    depends_on:
          - nginx
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mysql55

  mariadb55:
    image: mariadb:5.5
    ports:
      - "${MARIADB_55_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data-55:/var/lib/mariadb/55
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mariadb55

  mariadb100:
    image: mariadb:10.0
    ports:
      - "${MARIADB_100_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data-100:/var/lib/mariadb/100
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mariadb100

  mariadb101:
    image: mariadb:10.1
    ports:
      - "${MARIADB_101_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data-101:/var/lib/mariadb/101
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mariadb101

  mariadb102:
    image: mariadb:10.2
    ports:
      - "${MARIADB_102_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data-102:/var/lib/mariadb/102
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mariadb102

  mariadb103:
    image: mariadb:10.3
    ports:
      - "${MARIADB_103_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data-103:/var/lib/mariadb/103
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - php-dev
    restart: always
    container_name: os_dev_mariadb103

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - phpmyadmin-data:/var/lib/phpmyadminos

    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOSTS: mysql55,mysql56,mysql57,mariadb55,mariadb100,mariadb101,mariadb102.mariadb103
    networks:
      - php-dev
    restart: always
    container_name: os_dev_phpmyadmin

volumes:
    mysql-data-55:
    mysql-data-56:
    mysql-data-57:
    mariadb-data-55:
    mariadb-data-100:
    mariadb-data-101:
    mariadb-data-102:
    mariadb-data-103:
    phpmyadmin-data:

networks:
  php-dev:
