version: "2"
services:

  nginx:
    image: samanthajayasinghe/php-dev-env-nginx
    ports:
      - "80:80"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
       - php-dev

  php-5.6:
    image: samanthajayasinghe/php-dev-env-php56
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev

  php-7.0:
    image: samanthajayasinghe/php-dev-env-php70
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev

  php-7.1:
    image: samanthajayasinghe/php-dev-env-php71
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev

  php-7.2:
     image: samanthajayasinghe/php-dev-env-php72
     working_dir: ${REMOTE_SRC}
     environment:
       HIST_FILE: /root/.bash_history
     volumes:
       - ${LOCAL_SRC}:${REMOTE_SRC}
       - $HOME/.bash_history:/root/.bash_history
     networks:
       - php-dev

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
          - nginx
    networks:
      - php-dev

  mariadb:
    image: mariadb:10.2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data:/var/lib/mysql
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - php-dev

volumes:
    pgsql-data:
    mysql-data:
    web-data:
    mariadb-data:

networks:
  php-dev:
